language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -y cmake build-essential 
  
install:
  - pip install .

before_script:
  - cd ${HOME}
  - git clone -b stable_7Aug2019 https://github.com/lammps/lammps.git
  - cd lammps
  - mkdir build
  - cd build
  - cmake -D PKG_PYTHON=on -D PKG_MC=on -D PKG_MOLECULE=on -D PKG_RIGID=on -D PKG_USER-MISC=on -D BUILD_LIB=on -D BUILD_SHARED_LIBS=on -D CMAKE_INSTALL_PREFIX=${VIRTUAL_ENV} ../cmake
  - make
  - make install
  - python_package_dir=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
  - cp ../python/lammps.py ${python_package_dir}
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${VIRTUAL_ENV}/lib
  - cd ${TRAVIS_BUILD_DIR}

script:
  - pytest
