language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -y cmake build-essential 
  
install:
  - pip install .

before_script:
  - cd ${HOME}
  - git clone -b stable_7Aug2019 https://github.com/lammps/lammps.git
  - cd lammps
  - mkdir build
  - cd build
  - cmake -D PKG_PYTHON=on -D PKG_MC=on -D PKG_MOLECULE=on -D PKG_RIGID=on  -D BUILD_LIB=on -D BUILD_|
  SHARED_LIBS=on -D CMAKE_INSTALL_PREFIX=${HOME}/.local ../cmake
  - make
  - make install

script:
  - pytest

env:
  - PATH=${HOME}/.local/bin:$PATH
  - LD_LIBRARY_PATH=${HOME}/.local/lib:$LD_LIBRARY_PATH
  - PYTHONPATH=${PYTHONPATH}:${HOME}/.local/lib/python3/dist-packages/
